language: rust
rust:
  - nightly
  - stable
  - beta
  - 1.40.0
os:
  - linux
  - osx
  - windows

addons:
  apt:
    packages:
      - valgrind

env:
  LOOM_MAX_BRANCHES=100000
  RUSTFLAGS="--deny warnings "

script:
  - cargo build
  - cargo test
  - cargo test --no-default-features
  - cargo test --no-default-features --features std
  - cargo test --no-default-features --features async
  # Adding an extra delay in some places in the code. Makes the tests hit other edge cases.
  - RUSTFLAGS+="--cfg oneshot_test_delay" cargo test
  # Use loom to test memory correctness further
  - RUSTFLAGS+="--cfg loom" cargo test
  - RUSTFLAGS+="--cfg loom" cargo test --no-default-features
  - RUSTFLAGS+="--cfg loom" cargo test --no-default-features --features std
  - RUSTFLAGS+="--cfg loom" cargo test --no-default-features --features async
  - if [[ $(uname -s) == "Linux" ]]; then
      cargo install cargo-valgrind &&
      cargo valgrind --test sync &&
      ./check_mem_leaks.sh &&
      RUSTFLAGS+="--cfg oneshot_test_delay" ./check_mem_leaks.sh;
    fi
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" && $(uname -s) == "Linux" ]]; then
      rustup component add rustfmt-preview;
      rustfmt --version;
      cargo fmt -- --check;
    else
      echo "Not checking formatting on this build";
    fi

notifications:
  email:
    on_success: never
    on_failure: never
