language: rust
rust:
  - nightly
  - stable
  - beta
  - 1.39.0
os:
  - linux
  - osx
  - windows

script:
  - cargo build --verbose
  - cargo test --verbose
  # Adding an extra delay in some places in the code. Makes the tests hit other edge cases.
  - cargo test --features test-delay --verbose
  - RUSTFLAGS="--cfg loom" cargo test
  - if [[ "${TRAVIS_RUST_VERSION}" = "stable" && $(uname -s) == "Linux" ]]; then
      rustup component add rustfmt-preview;
      rustfmt --version;
      cargo fmt -- --check;
    else
      echo "Not checking formatting on this build";
    fi

notifications:
  email:
    on_success: never
    on_failure: never
