[package]
name = "oneshot"
version = "0.1.0"
authors = ["Linus Färnstrand <faern@faern.net>"]
license = "MIT OR Apache-2.0"
readme = "README.md"

description = """
Oneshot spsc channel with lock-free non-blocking send and a receiver supporting both thread
blocking receive operations as well as Future based async polling.
"""

repository = "https://github.com/faern/oneshot"
keywords = ["oneshot", "spsc", "async", "sync", "channel"]
categories = ["asynchronous", "concurrency"]
edition = "2018"

[target.'cfg(loom)'.dependencies]
loom = "0.3.2"

[dev-dependencies]
criterion = "0.3"

[target.'cfg(not(loom))'.dev-dependencies]
tokio = { version = "0.2.20", features = ["rt-threaded", "macros", "time"] }

[[bench]]
name = "benches"
harness = false
