name: Rust formatting check
on:
  push:
    paths:
      - .github/workflows/rustfmt.yml
      - '**/*.rs'
  pull_request:
  workflow_dispatch:
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Check formatting
        run: |
          rustfmt --version
          cargo fmt -- --check
