name: Rust linting and formatting
on:
  pull_request:
    paths:
      - .github/workflows/*.yml
      - '**/*.rs'
  workflow_dispatch:
jobs:
  clippy-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
          override: true

      - name: Clippy check
        run: |
          export RUSTFLAGS="--deny warnings"
          time cargo clippy --verbose

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: rustfmt
          override: true

      - name: Check formatting
        run: |
          rustfmt --version
          cargo fmt -- --check
